feat: STOR-549
Farm-Investimentos/front-mfe-components pull request #1065
Opened 2023-04-19 19:04 UTC by KainanGB

Added two new props to ResourceMetaInfo:

| Before | After |
| ------- |-------|
| ![image](https://user-images.githubusercontent.com/55860684/233174854-5274d16d-bcb5-4f60-bdbc-79af1e27a865.png) | ![image](https://user-images.githubusercontent.com/55860684/233174292-b3401c8b-666e-4f47-99fd-7b85e415c9d4.png) |

2023-04-19 19:08 UTC, christian-benseler-farm requested changes

2023-04-19 19:08 UTC, christian-benseler-farm commented on src/components/ResourceMetaInfo/ResourceMetaInfo.vue
> +		const showCreatedBy = computed(
Criar teste unitário.

2023-04-19 19:08 UTC, christian-benseler-farm commented on src/components/ResourceMetaInfo/ResourceMetaInfo.vue
> +		const showCreatedHours = computed(
Criar teste unitário.

2023-04-19 19:37 UTC, KainanGB commented on src/components/ResourceMetaInfo/ResourceMetaInfo.vue
> +		const showCreatedBy = computed(
Feito

2023-04-19 19:37 UTC, KainanGB commented on src/components/ResourceMetaInfo/ResourceMetaInfo.vue
> +		const showCreatedHours = computed(
Feito

2023-04-20 16:42 UTC, christian-benseler-farm commented
@Dirceu-Souza-Rezende @everton-ribeiro podem avaliar?

2023-04-20 17:55 UTC, Dirceu-Souza-Rezende approved these changes

2023-04-20 18:21 UTC, merged