feat: STOR-16
Farm-Investimentos/front-mfe-components pull request #316
Opened 2022-07-29 19:27 UTC by Dirceu-Souza-Rezende

2022-07-29 19:38 UTC, christian-benseler-farm requested changes

2022-07-29 19:38 UTC, christian-benseler-farm commented on src/components/MultipleFilePicker/MultipleFilePicker.scss
> +		.v-icon {
Existe algum v-icon sendo usado no template?

2022-07-29 19:38 UTC, christian-benseler-farm commented on src/components/MultipleFilePicker/MultipleFilePicker.scss
> +		.v-btn {
Existe algum v-btn?

2022-07-29 19:38 UTC, christian-benseler-farm commented on package.json
> +		"@farm-investimentos/front-mfe-libs-ts": "^1.0.2",
Eu coloquei agora pouco esse cara no devDependencies.
Como tem outros ajustes a fazer, você tira de lá?

Ai, uma dúvida: muda alguma coisa no bundle final fazer o import do helpers de sizeFile direto do caminho dele ao invés da raiz?

2022-07-29 20:07 UTC, Dirceu-Souza-Rezende commented on src/components/MultipleFilePicker/MultipleFilePicker.scss
> +		.v-icon {
Antes estava utilizando v-icon e v-btn, alterei para farm-icon e farm-btn

2022-07-29 20:17 UTC, Dirceu-Souza-Rezende commented on package.json
> +		"@farm-investimentos/front-mfe-libs-ts": "^1.0.2",
Retirei do dependecies. Acho que para o bundle em si não. Se não importar direto da raiz perde a tipagem e caso alterarmos a localização das pastas teria que alterar em todos os locais. 
![image](https://user-images.githubusercontent.com/96076023/181836432-55706a10-5cae-4895-8e88-61c0fc220f9c.png)
![image](https://user-images.githubusercontent.com/96076023/181836911-d85f933e-a8b0-4c5e-890e-4223093add8d.png)

2022-07-29 20:28 UTC, Dirceu-Souza-Rezende commented on package.json
> +		"@farm-investimentos/front-mfe-libs-ts": "^1.0.2",
Acho que para o bundle pode diminuir também o tamanho se tiver mais de uma interface, helper e formatter importado no arquivo, porque só vai ser adicionado na raiz, não vai precisar importar diversas linhas.
![image](https://user-images.githubusercontent.com/96076023/181838398-210e486b-6b36-481f-9ece-75853af22ea8.png)

2022-08-01 09:00 UTC, christian-benseler-farm approved these changes

2022-08-01 09:00 UTC, merged