feat: STOR-34
Farm-Investimentos/front-mfe-components pull request #399
Opened 2022-08-18 20:42 UTC by Dirceu-Souza-Rezende

2022-08-18 20:50 UTC, christian-benseler-farm requested changes

2022-08-18 20:50 UTC, christian-benseler-farm commented on src/components/Loader/Loader.scss
> +	z-index: 10;
Não sei se esse 10 chumbado vai funcionar.
Acho que teria que pegar dinamicamente o maior z-index da página e colocar o z-index via atributo _style_.
Aqui como pegar a informação
https://bobbyhadz.com/blog/javascript-find-highest-z-index-on-page

2022-08-18 21:12 UTC, Dirceu-Souza-Rezende commented on src/components/Loader/Loader.scss
> +	z-index: 10;
Alterado.

2022-08-19 12:34 UTC, christian-benseler-farm approved these changes

2022-08-19 12:39 UTC, merged