feat: STOR-50
Farm-Investimentos/front-mfe-components pull request #429
Opened 2022-08-29 20:58 UTC by KainanGB

2022-08-29 21:04 UTC, Dirceu-Souza-Rezende requested changes

2022-08-29 21:04 UTC, Dirceu-Souza-Rezende commented on src/components/IdCaption/IdCaption.vue
> +	<div class="idcaption" :link="link">
Retirar :link="link"

2022-08-29 21:04 UTC, Dirceu-Souza-Rezende commented on src/main.ts
> +export * from './components/IdCaption';
Não deveria ser apenas um export?

2022-08-30 12:13 UTC, christian-benseler-farm requested changes

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.scss
> +		margin-right: 0.3rem;
Deixar em px, estamos mudando tudo pra essa unidade.

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.stories.js
> +
Reirar o espaço.

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.stories.js
> +        <template v-slot:title="{}">
Precisa desse ="{}"?
Não pode ser só
`
<template v-slot:title>
`
se está em branco?

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.stories.js
> +        <template v-slot:title="{}">
Idem aqui sobre o {}

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.vue
> +				<farm-btn @click="$emit('onLinkClick')" icon color="gray" v-if="link">
Ajustar a ordem, deixar os event handlers como último (no caso, o @click)

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.vue
> +		const hasTitle = computed(() => {
Não precisa do return em uma arrow function de um statement só, já que se for com 1 instrução retorna ela mesmo.

`
const hasTitle = computed(() => slots.title);
`

2022-08-30 12:13 UTC, christian-benseler-farm commented on src/components/IdCaption/IdCaption.vue
> +		const hasSubtitle = computed(() => {
Idem.

2022-08-30 13:21 UTC, Dirceu-Souza-Rezende approved these changes

2022-08-30 18:10 UTC, Dirceu-Souza-Rezende approved these changes

2022-08-30 18:17 UTC, christian-benseler-farm approved these changes

2022-08-30 18:17 UTC, merged