feat STOR-2: RadioGroup
Farm-Investimentos/front-mfe-components pull request #476
Opened 2022-09-22 14:10 UTC by wesley-santana

2022-09-22 19:18 UTC, christian-benseler-farm requested changes

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.scss
> +// input[type='radio']:hover:checked {
Retirar comentário.

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.scss
> +*,
Esse * não afeta o escopo global do css né?

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.stories.js
> +	components: { 'farm-radio-group': RadioGroup },
Não precisa desse import; os componentes já são "auto-adicionados" no Vue pra ser usado.

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.stories.js
> +	component: RadioGroup,
Colorcar na descrição qual a tag será usada.
Pode ver como está no https://storybook.plataforma.portalfarm.com.br/index.html?path=/docs/display-idcaption--primary

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.scss
> +    width: 0.60em;
Deixar fixo em px.

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.scss
> +    box-shadow: inset 1em 1em var(--radio-group-color);
Deixar fixo em px.

2022-09-22 19:18 UTC, christian-benseler-farm commented on src/components/RadioGroup/RadioGroup.scss
> +    border: none;
Deixar tudo em px e não em.

2022-09-23 12:54 UTC, wesley-santana commented on src/components/RadioGroup/RadioGroup.scss
> +*,
Acredito que sim por causa do scoped

2022-09-23 13:07 UTC, wesley-santana commented on src/components/RadioGroup/RadioGroup.scss
> +*,
![image](https://user-images.githubusercontent.com/69155527/191967061-33e41243-9258-4f0b-b496-593b5da39bbe.png)

2022-09-23 13:15 UTC, merged