cálculo do z-index
Farm-Investimentos/front-mfe-components pull request #549
Opened 2022-10-04 23:53 UTC by victormarques92

2022-10-05 12:30 UTC, christian-benseler-farm requested changes

2022-10-05 12:30 UTC, christian-benseler-farm commented on src/components/Modal/Modal.vue
> +		const zIndex = Math.max(
Tem uma pasta src/helpers, pode encapsular esse cálculo todo do zIndex numa função e mover para lá (vamos precisar disso em outros componentes).

2022-10-05 14:23 UTC, christian-benseler-farm commented
@Dirceu-Souza-Rezende veja se tem algo a acrescentar aqui, já que você que fez a implementação no outro componente!

2022-10-05 15:15 UTC, Dirceu-Souza-Rezende commented
> @Dirceu-Souza-Rezende veja se tem algo a acrescentar aqui, já que você que fez a implementação no outro componente!

Acho que está ok, @christian-benseler-farm . Só encapsular em uma função como você comentou e alterar no Loader também.

2022-10-05 17:26 UTC, christian-benseler-farm commented
@victormarques92 ficaram faltando esses ajustes aqui. Valeu!

2022-10-07 10:40 UTC, christian-benseler-farm commented
@victormarques92 só mudei aqui a função pra ela retornar o valor do zIndex e não o objeto como um todo.

2022-10-07 10:40 UTC, merged