feat: STOR-310
Farm-Investimentos/front-mfe-components pull request #820
Opened 2022-12-20 19:37 UTC by Dirceu-Souza-Rezende

Implementation:
![image](https://user-images.githubusercontent.com/96076023/208748008-fa36b314-2c24-4cd2-bc2d-2d5376ca1f71.png)
![image](https://user-images.githubusercontent.com/96076023/208748020-f8987336-669e-492b-964e-32b721f65192.png)
![image](https://user-images.githubusercontent.com/96076023/208748132-55a6c032-4e9e-4f5c-9323-a0b3d5968856.png)

2022-12-20 20:19 UTC, christian-benseler-farm commented
@KainanGB  @higorfarm se puderem ajudar no code review desse PR :)

2022-12-20 22:46 UTC, christian-benseler-farm commented on src/components/Select/Select.vue
> +			if (
Não é mais fácil só retornar o valor da comparação do if?

`return multiple.value && multipleValues.value.findIndex(val => val === item.value) !== -1`

E também fazer um spec pra esse método.

2022-12-21 21:00 UTC, higorfarm approved these changes

2022-12-21 21:03 UTC, KainanGB approved these changes

2022-12-21 22:45 UTC, christian-benseler-farm requested changes

2022-12-21 22:45 UTC, christian-benseler-farm commented on src/components/Select/Select.vue
> +		const isChecked = item => {
Faltou um teste unitário.

2022-12-21 22:45 UTC, christian-benseler-farm commented on src/components/Select/Select.vue
> +			if (multiple.value && Array.isArray(innerValue.value) && innerValue.value.length > 0) {
Rola colocar isso em uma outra função e fazer um teste? A função onde esse trecho está ficou bem grande e tem um nivel de complexidade alto.

2022-12-22 14:01 UTC, christian-benseler-farm approved these changes

2022-12-22 17:22 UTC, christian-benseler-farm approved these changes

2022-12-22 17:22 UTC, merged